version: '3.3'



services:
  user_service:
    container_name: user_service
    build:
      context: ./user_service
    volumes:
     - ./user_service:/user_service
    working_dir: /user_service/code
    networks:
      - user
    depends_on:
      - event_bus

  log_service:
    container_name: log_service
    build:
     context: ./log_service
    volumes:
       - ./log_service:/log_service
    working_dir: /log_service/code
    networks:
        - user
    depends_on:
        - event_bus


  event_bus:
    container_name: event_bus
    image: spotify/kafka
    networks:
      - user

networks:
  user:
