version: '3.3'



services:
  user_service:
    container_name: user_service
    build:
      context: ./user_service
    volumes:
     - ./user_service:/user_service
    working_dir: /user_service/code
    links:
     - event_bus
    networks:
      - user

  log_service:
    container_name: log_service
    build:
     context: ./log_service
    volumes:
       - ./log_service:/log_service
    working_dir: /log_service/code
    networks:
        - user
    links:
        - event_bus

  legacy_user_service:
    container_name: legacy_user_service
    build:
      context: ./legacy_user_service
    volumes:
     - ./legacy_user_service:/legacy_user_service
    working_dir: /legacy_user_service/code
    links:
     - event_bus
    networks:
      - legacy_user_internal


#  event_bus:
#    container_name: event_bus
#    image: spotify/kafka
#    networks:
#      - user
#      - legacy_user_internal
#    ports:
#      - 2181:2181
#      - 2888:2888
#      - 3888:3888
#      - 9092:9092



#-------------Legacy Sync Network section



  event_bus:
    container_name: event_bus
#    image: debezium/kafka
    image: landoop/fast-data-dev
    ports:
     - 9092:9092
     - 3030:3030
    networks:
        - user
        - legacy_user_internal
    environment:
     - CONFIG_STORAGE_TOPIC=my_connect_configs"
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - CONNECTORS=org.apache.kafka.connect.tools.MockSinkConnector



  mysql:
    image: debezium/example-mysql
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw
    networks:
      - legacy_user_internal

  connect:
    image: debezium/connect:0.7
    ports:
     - 8083:8083
     - 5005:5005
    links:
     - event_bus
     - mysql
    environment:
     - BOOTSTRAP_SERVERS=event_bus:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
    networks:
      - legacy_user_internal


networks:
  user:
  legacy_user_internal:
